export default function fingerprint() {
    return (
        <>
            <h1>Fingerprint</h1>
            <p>
                Fingerprint is a unique identifier generated by the web browser
                when a user visits a website. Fingerprinting is a technique used
                to track users across websites without using cookies
            </p>
        </>
    );
}
